### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/HistomicsUI#145]
- [x] Set up keyboard short cuts to toggle drawing / stop drawing an annotation.  If no annotation is selected, perhaps this would open the new annotation dialog. #154

- [x] Set up keyboard short cuts to pick the style group. #155

- [x] Also, set up a keyboard shortcut to close a polygon (same action as double clicking when drawing a polygon). #157

- [ ] In the new annotation dialog, it would be nice if the keyboard could perform the default action.  Broadly, in any dialog, it would be nice to do something like `$('.btn').prop('tabindex', '0')`. #158
